### ISSUE TITLE
Document not very clear

### ISSUE THREAD

**Issue by accilies** [xcray/Apple_Airport_hass_devicetracker_and_Internet_Connection_Sensor#2]
Can you explain further on how is the first step achieved? 

1. Enable syslog and set target address on airport router

I have HA setup on my Mac.

**Comment by xcray** [comment]
This step could be accomplished by the Windows version of "Airport Utility". Mac version doesn't have such an option.
1. Open "Airport Utility" on Windows, wait for the discovery of your Airport Router.
2. Click "Manual Setup", then "Advanced", under the tab of "Logging and Statistics", you can set the "Syslog Destination Address", which I mentioned as "target address".
3. Click "Update" and wait for the reboot of your router.
